name: CI/CD Astro to AWS

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.12.0'
          cache: 'npm'

      - name: Instalar dependencias y Tests
        run: |
          npm install
          npm test # Aquí se ejecutan tus pruebas unitarias
      
      - name: cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
              ${{ runner.os }}-node-

      - name: Build de Astro
        run: npm run build
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout código
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init & Apply
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform apply -auto-approve -var="public_key=${{ secrets.SSH_PUBLIC_KEY }}"
          echo "EC2_IP=$(terraform output -raw instance_ip)" >> $GITHUB_ENV

      - name: Deploy a la instancia EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_IP }}
          username: ec2-user # Usuario por defecto en Amazon Linux
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/var/www/html"
          strip_components: 1 # Para que no cree una carpeta 'dist' dentro de html